/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { RewardListRelationFilter } from "../../reward/base/RewardListRelationFilter";
import { ScoreListRelationFilter } from "../../score/base/ScoreListRelationFilter";
import { EnumPlayerTypeField } from "./EnumPlayerTypeField";

@InputType()
class PlayerWhereInput {
  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  currentScore?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => RewardListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RewardListRelationFilter)
  @IsOptional()
  @Field(() => RewardListRelationFilter, {
    nullable: true,
  })
  rewards?: RewardListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ScoreListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ScoreListRelationFilter)
  @IsOptional()
  @Field(() => ScoreListRelationFilter, {
    nullable: true,
  })
  scores?: ScoreListRelationFilter;

  @ApiProperty({
    required: false,
    enum: EnumPlayerTypeField,
  })
  @IsEnum(EnumPlayerTypeField)
  @IsOptional()
  @Field(() => EnumPlayerTypeField, {
    nullable: true,
  })
  typeField?: "Option1";
}

export { PlayerWhereInput as PlayerWhereInput };
